### ISSUE TITLE
PHP 8.2 Deprecated: Creation of dynamic property 

### ISSUE THREAD

**Issue by robsonala** [google/php-crc32#13]
Hi,

Since I migrate from PHP 8.1 I started having deprecation issue about the creation of dynamic property (https://wiki.php.net/rfc/deprecate_dynamic_properties)

`Deprecated: Creation of dynamic property Google\CRC32\Builtin::$algo is deprecated in /var/www/vendor/google/crc32/src/Builtin.php on line 57`

**Comment by bramp** [comment]
Yes, I think this was fixed in https://github.com/google/php-crc32/pull/12
