### ISSUE TITLE
v0.1.0 deprecation warnings for PHP 8.2

### ISSUE THREAD

**Issue by saulius-cepauskas-vg** [google/php-crc32#14]
Current tagged version throws: 
```
Deprecated: Creation of dynamic property Google\CRC32\Builtin::$algo is deprecated
```

I see master branch contains fixes already for it, could new version be tagged?

**Comment by saulius-cepauskas-vg** [comment]
Temporal workaround till version tagged could be

```
composer require google/crc32:"dev-master as 0.1.1"
```

**Comment by rogervila** [comment]
@google-admin Who can release a [new tag from the master branch](https://github.com/google/php-crc32/compare/v0.1.0...master)?

**Comment by oldcodefork** [comment]
> @google-admin Who can release a new tag from the master branch?

CC @bramp ?

**Comment by robsonala** [comment]
@bramp Would be possible create the new release so the packages dependent of this repo would stop failing?

**Comment by bramp** [comment]
Sorry for being so behind on this. I spent sometime this weekend bumping everything to PHP 8.2, but that broke phpunit and some other deprecation warnings appeared.

Travis (CI) is no longer supported, so I'm also moving to Github actions, so I can test across all versions of PHP.  Until then please use the workaround here: https://github.com/google/php-crc32/issues/14#issuecomment-1410043810

**Comment by bramp** [comment]
Ok I've finished all the changes needed for this to build cleanly on PHP 7.4 though to PHP 8.2.

I've now published this officially as v0.2.0.

However, after I made all the changes, and re-run the benchmarks, its apparent the PHP 8.0 has a really fast CRC implementation built in. So if you are targeting that version I would recommend to no longer use this package. For that reason I'm going to officially deprecate this package. v0.1.0 will still work for old PHPs (e.g 5-7), v0.2.0 for newer PHPs (7-8). But if you are on 8, transition to https://www.php.net/manual/en/ref.hash.php

**Comment by nesl247** [comment]
> Ok I've finished all the changes needed for this to build cleanly on PHP 7.4 though to PHP 8.2.
> 
> I've now published this officially as v0.2.0.
> 
> However, after I made all the changes, and re-run the benchmarks, its apparent the PHP 8.0 has a really fast CRC implementation built in. So if you are targeting that version I would recommend to no longer use this package. For that reason I'm going to officially deprecate this package. v0.1.0 will still work for old PHPs (e.g 5-7), v0.2.0 for newer PHPs (7-8). But if you are on 8, transition to [php.net/manual/en/ref.hash.php](https://www.php.net/manual/en/ref.hash.php)

One benefit to this library is the compatibility with AWS Redshift's `crc32` function. It's `crc32c` I believe, so maybe worth keeping this not deprecated?

**Comment by bramp** [comment]
The reason I wrote this library was fast crc32c when interacting with GCS. crc32c is popular in storage systems, so it doesn't surprise me if others use it.  However, I added native (but slow) crc32c support to PHP in 7.4 (https://externals.io/message/104588#104621) but since 8.0 someone made it super fast (with intel sse 4.2 instructions)

So the value of this library/extension that bundles https://github.com/google/crc32c may not be there anymore.

As I said I'll keep the extension around, but I don't know what use case it solves anymore in modern PHP.

**Comment by nesl247** [comment]
> The reason I wrote this library was fast crc32c when interacting with GCS. crc32c is popular in storage systems, so it doesn't surprise me if others use it. However, I added native (but slow) crc32c support to PHP in 7.4 ([externals.io/message/104588#104621](https://externals.io/message/104588#104621)) but since 8.0 someone made it super fast (with intel sse 4.2 instructions)
> 
> So the value of this library/extension that bundles [google/crc32c](https://github.com/google/crc32c) may not be there anymore.
> 
> As I said I'll keep the extension around, but I don't know what use case it solves anymore in modern PHP.

I didn't catch the `crc32c` there at first, I only knew of `crc32` itself. Thanks!
